name: Deploy Staging Website

on: "pull_request"

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn

      - name: Linting and typechecks
        run: |-
          yarn lint
          yarn typecheck

      - name: Deploy via vercel
        id: deploy
        run: |-
          yarn

          mkdir .vercel
          echo '{ "projectId": "${{ secrets.VERCEL_PROJECT_ID }}", "orgId": "${{ secrets.VERCEL_ORG_ID}}" }' \
            > .vercel/project.json

          vercel --token=${{ secrets.VERCEL_TOKEN }} > url.txt
          echo "::set-output name=url::$(cat url.txt)"

      - name: Create deployment entry
        id: deployment
        uses: actions/github-script@v5
        env:
          URL: ${{ steps.deploy.outputs.url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log({ github, rest: github.rest });
            const deployment = await github.rest.repos.createDeployment({
              ...context.repo,
              ref: "${{ github.sha }}",
              required_contexts: [],
              environment: process.env.URL,
              description: `Staging environment available at ${URL}`
            });

            const deployments = await github.rest.repos.listDeployments({...context.repo});
            console.log({ deployments, deployment })

            core.setOutput("id", deployment.data.id);

      - name: Add comment with deployment url
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;

            const comments = await github.rest.issues.listComments({issue_number, owner, repo});
            const comment = comments.data.find(comment => comment.body.startsWith('<!-- automated PR comment -->'));
            if (comment) {
              github.issues.deleteComment({issue_number, owner, repo, comment_id: comment.id});
            }

            const body = `<!-- automated PR comment -->\n\nPR has been deployed to: ${{ steps.deploy.outputs.url }}`
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            });

      - name: On success
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: '${{ steps.deployment.outputs.id }}',
              state: 'success'
            });

      - name: On error
        if: failure() || cancelled()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: '${{ steps.deployment.outputs.id }}',
              state: 'failure'
            });
